<?php
include 'head.php';
?>
<section id="budgeting">
    <div class="container-fluid generic-container">
        <div class="row">
            <div class="col-sm-6 generic-custom-description">
                <h2>
                    Design &amp; Budgeting</h2>
                Our systems accept excel data input i.e schemes allocated, indicating on the map that’s
                (integrated on the system), exact location of the schemes. This helps you in planning
                logistics of material transportation to the site, the route to use, and the type of vehicle to
                use. You’ll be able to plan for a cluster schemes to co-ordinate their materials from one
                central point easily.
                From the design BOQ or pegging data the system generates all the materials required to
                completely construct a specific scheme. In addition, it generates the labour required and a
                budget for the scheme.
                Once the materials are generated the Design Engineers has the privilege to approve or
                reject the output materials before they’re exported to the construction engineer for scheme
                allocation, requisition authorization and Gantt chart preparation.
                This is swiftly done by sending a notification to the construction engineer for their action
                after Design Engineer has approved a scheme.
            </div>
            <div class="col-sm-6 generic-custom-img">
                <img src="../../img/1.jpg" alt=""/>
            </div>
        </div>
    </div>
</section>
<section id="StoreManagement">
    <div class="container-fluid generic-container">
        <div class="row">
            <div class="col-sm-6 generic-custom-img">
                <img src="../../img/store.jpg" alt="StoreManagement"/>
            </div>
            <div class="col-sm-6 generic-custom-description">
                <h2>
                  Store Management  
                </h2>
                <p>
                    In the store module which has user permissions to store manager and procurement officers.
   The system indicates the inventory level for all the materials i.e low, critically low, high, etc.
   Procurement officers can generate purchase orders through the system and accept
   materials to store as procured and delivered.
   The store manager can issue materials as approved by the construction engineer, to the
   construction team/sub-contractor assigned to that scheme.
   Every transaction of the materials, IN/OUT of the store is captured in the inventory log.
   A print out of the issued materials is generated indicating the balance materials owed to the
   construction team for the scheme completion.
                </p>
            </div>
        </div>
    </div>
</section>
<section id="WorkProgress.">
    <div class="container-fluid generic-container">
        <div class="row">
            <div class="col-sm-6 generic-custom-description">
                <h2>
                  Work Progress.   
                </h2>
                <p>
                   After the allocation of the scheme to a subcontractor or construction teams, the system
   gives a platform for them to update their work progress, capturing the work assigned and
   work completed within a specific period of time as required by the construction engineer.
   The system generates the percentage progress of every scheme once its been updated.
   From the print out generated by the system, the accounts can be able to settle advance
   payments for the jobs already completed by the construction teams.  
                </p>
            </div>
            <div class="col-sm-6 generic-custom-img">
                <img src="../../img/cumulative_work_progress.png" alt="work_progress"/>
            </div>
        </div>
    </div>
</section>
<section id="Reporting">
    <div class="container-fluid generic-container">
        <div class="row">
            <div class="col-sm-6 generic-custom-img">
               <img src="../../img/Training.jpg" alt=""/> 
            </div>
            <div class="col-sm-6 generic-custom-description">
                <h2>
                 Reporting
                </h2>
                <p>
                 In reporting the system captures both the individual and overall project progress, it has a
   chart indicating the overall progress accumulative work completed, and accumulative work
   in progress. Either on track or under construction.
   This is important so that you’re able to predetermine whether you’re in a position to
   complete the project within the given period.
   Material usage and reporting.
   The system generates a report of materials generated against materials issued for both
   individual schemes and overall project.
   When completing the project, you’ll require to identify what materials you’ll need to
   procure so that at the end of the project you’ll not have unutilized materials.   
                </p>
            </div>
        </div>
    </div>
</section>
<section id="GanttChart">
    <div class="container-fluid generic-container">
        <div class="row">
            <div class="col-sm-6 generic-custom-description">
                <h2>
                   Gantt Chart 
                </h2>
                <p>
                   A Gantt chart is a chart in which a series of horizontal lines shows the amount of work done,
   r production completed in a certain period of time in relation to the amount planned for
   those periods.
   Emeran systems we care about you completing the project on time.
   The system generates an editable Gantt chart with the amount of work to be done on a
   scheme and the construction engineer is required to set the period proposed to be taken to
   completely construct the scheme.
   This can be printed and a copy issued to the construction team for them to hit their target.  
                </p>
            </div>
            <div class="col-sm-6 generic-custom-img">
                <img src="../../img/Gantt_chart.png" alt=""/>
            </div>
        </div>
    </div>
</section>
<section id="MaterialReconciliation">
    <div class="container-fluid generic-container">
        <div class="row">
            <div class="col-sm-6 generic-custom-img">
                <img src="../../img/Material_reconciliation.png" alt=""/>
            </div>
            <div class="col-sm-6 generic-custom-description">
                <h2>
                  Material Reconciliation  
                </h2>
                <p>
                    Material reconciliation Is key in every construction industry, where we reconcile materials
   issued for a scheme and materials used to construct the scheme.
   As built data is collected and fed into the system and it does the rest of reconciliation
   indicating if there’s materials that are unaccounted for.
                </p>
            </div>
        </div>
    </div>
</section>
 

<div style="display: none;">
    <p>Inspection $ handover
   Once a scheme is complete, there’s supervision to ensure it was constructed to standard
   and its ready for flag-off. The system keeps the record of all inspected and hand-over
   schemes as approved by the client.
 
   

   Field survey &amp; Design.
   Our surveyors are trained to collect the data required on field for electrification projects,
   they’re trained on customer relations to ensure effective cooperation with the people
   involved during the project implementation.
   This has been a great advantage to our effectiveness in implementing our projects and
   activities assigned on site.
   We’ve a diversified database of our trained surveyors to assist handle areas where the
   customer involved can only communicate in their local language.
   We have regular trainings and brainstorming sessions with our staffs and trainees i.e
   designers &amp; surveyors on how to effectively deliver on electrification projects. As a result,
   we’ve been able to apply technological solutions to help with speed accuracy and efficiency
   on our designs.

   Autocad designs
   Data communication between the surveyors and AutoCAD designers (Back office team),
   contributes much to the speed and quality of designs achieved. We’ve created and
   implemented efficient mediums of data transfer between the departments involved. i.e the
   surveyor and the ack-office team. Data from the field is now received in real-time by the
   back-office team. We’ve improved the interaction and communication between the
   surveyors and the back-office team to understand the designs much better.
   Field database (Utility database)
   Emeran being a power and technology company with professionals we’ve been able to
   develop an additional feature to the system that converts surveyor’s field data to ‘up
   loadable’ data to client’s power utility database
   This has proved effective since one was initially required to manually update the same data
   to the client’s database.
   In our projects in Kenya, we’ve developed an additional feature that updates surveyor’s data
   to Kenya power field database.
   As-built
   Our field personnel have been trained and equipment provided that will help collect all
   major data required for As constructed schemes projects
   From the data collected its uploaded on our management system and a list of all materials
   used on the project is generated. This data is necessary for materials reconciliation and
   invoicing. The data will also be used to generate AutoCAD files for as constructed schemes
   and update the power utility database.

   MV &amp; LV Construction
   Pegging – Our data applications are user friendly and easy to learn making it easier for
   construction teams to easily use them during pegging. (Pegging is marking the exact position
   to erect the pole and final route to be constructed.)
   Material requisition – Determining the materials required to construct a scheme/project
   completely can be tedious and erroneous, the system comes in hand by using the data
   pegged for final construction design, to generate materials required to fully construct the
   scheme to standard.
   The generated list once approved by construction engineer/manager is exported as is to
   store for material issuing, this makes material issuing process easy, fast and accurate.
   Construction standards - Emeran is proud to have qualified engineers passionate on their
   work, well trained site supervisors to ensure standards are observed during constructions.</p>
</div>
<div class="container-fluid generic-container container-contact">
    <div class="row fancy-background">
        <div class="col-sm-8">
            <h2>GET ON BOARD WITH EMERAN</h2>
            <p>Emeran system's team can provide the experience, expertise, resourses and materials you need.
                <br>
            Bank on our engineering teams.
            </p>
        </div>
        <div class="col-sm-4">
            <a href="#" class="btn fancy-button">
                Request More Information
            </a>
        </div>
    </div>
</div>
 <!--Footer Section-->
        <?php
        include '../../includes/footer/footer.php';
        ?>
